package com.bas.auction.core.crypto;

public class CertValidationError extends RuntimeException {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    public enum Type {
        REVOKED, VALIDITY_EXPIRED, NOT_YET_VALID, IIN_ABSENCE, NON_RES_ORG_ID_ABSENCE, EMAIL_ABSENCE, IIN_VALIDATION, BIN_VALIDATION, AUTH_DS_IIN_MISMATCH, NON_RES_ORG_ID_MISMATCH, NON_RES_EMAIL_MISMATCH, AUTH_DS_BIN_MISMATCH, FIRST_LAST_NAME_ABSENCE, FIRST_LAST_NAME_VALIDATION, CRL_FILE_NOT_FOUND, CRL_GENERATE_EXCEPTION, CRL_URL_IS_EMPTY, CRL_URL_IS_MALFORMED, CRL_DOWNLOAD_EXCEPTION, CRL_VERIFICATION_EXCEPTION, NO_CERT_FOR_CRL_VERIFICATION_EXCEPTION, BASE_CRL_NUMBER_IS_LESS_THEN_DELTA_CRL_BASE_NUMBER, CERT_PATH_VALIDATION_EXCEPTION, TRUSTED_ANCHOR_LIST_IS_EMPTY, OCSP_REQUEST_ERROR, OCSP_REVOKE_ERROR, OCSP_UNKNOWN_STATUS_ERROR, OCSP_RESP_SIGN_CHECK_FAILED, OCSP_RESP_SIGN_CERT_NOT_FOUND, OCSP_NONCE_NOT_MATCH, DIGITAL_SIGNATURE_KEY_USAGE_NOT_PRESENTED, NON_REPUDIATION_KEY_USAGE_NOT_PRESENTED, KEY_ENCIPHERMENT_KEY_USAGE_NOT_PRESENTED, DATA_ENCIPHERMENT_KEY_USAGE_NOT_PRESENTED, KEY_AGREEMENT_KEY_USAGE_NOT_PRESENTED, KEY_CERT_SIGN_KEY_USAGE_NOT_PRESENTED, CRL_SIGN_KEY_USAGE_NOT_PRESENTED, ENCIPHER_ONLY_KEY_USAGE_NOT_PRESENTED, DECIPHER_ONLY_KEY_USAGE_NOT_PRESENTED,;
    }

    private final Type type;

    public CertValidationError(Type type) {
        this.type = type;
    }

    public Type getType() {
        return type;
    }
}
